services:
  - type: web
    name: chirpy
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: chirpy-db
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: chirpy-db
    plan: free
